#!/bin/bash

# Queue (hour, day, week)
#BSUB -q day_lowmem

# Number of slots
#BSUB -n  8

# Slots per node (32 = fat nodes)
#BSUB -R "span[ptile=4]"

# Shared memory in MB 
#BSUB -R "rusage[mem=15000]"      

# Uncomment (remove one #) to request exclusive acccess to a node 
##BSUB -x 

# Use openmpi
#BSUB -a openmpi

# Job duration in hours
#BSUB -W 24:00

# Job name
#BSUB -J "test_htc"

# Job output file
#BSUB -o lsf%J.o

# Job error file
#BSUB -e lsf%J.e

# Load environment module (old system)
#module load hpc/vasp

# Load environment module (new system)
module load VASP

# Path to local per node and per job scratch dirs
# The contents will be copied to your working folder
# when the job terminates and then deleted
# Do use it for intensive non-parallel I/O 
export LOCAL_SCRATCHDIR=/scratch/tmp_$LSB_JOBID

# Define our variables here
export OMP_NUM_THREADS=1

# Now run the program
#mpirun -np 16 vasp # pre 5.4.1
mpirun -np 8 vasp_std > out

# A great deal of time and money has been put into 's dedicated research computing resources.                                                                                                                                             # Publications that have made use of these resources should make reference of that in the acknowledgements.    
